export const RESPONSE_CODES = {
    SERVER_NOT_WORKING : 1000,
    DATABASE_ERROR : 500,
    RESPONSE_OK : 200,
    RESPONSE_CREATED : 201,
    RESPONSE_NO_CONTENT : 204,
    UNAUTHORISED : 401,
    RESPONSE_ALREADY_EXIST : 209
}